repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
        -   id: check-yaml
        -   id: check-added-large-files

  -   repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.4
      hooks:
        -   id: ruff
            args: [--fix] # Automatically fix what it can
        -   id: ruff-format

  -   repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
        -   id: black

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
        -   id: mypy
        # Mypy can be slow, so you might run it manually or in CI
        # instead of every commit, but this is the setup for it.
        # Exclude tests if they are not fully typed yet.
        # exclude: ^tests/
        additional_dependencies: [ "types-requests" ] # Add types for 3rd party libs